title: Vieno's Planeswalking
description: ぽんこつプログラマの雑記
author: VienosNotes
logo: /static/img/avatar.png
github: https://github.com/VienosNotes
about: 雨漏りの雫のような生活

baseurl: ""
url: "http://vienosnotes.github.io/"

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
