title: Vieno's Planeswalking
description: ぽんこつプログラマの雑記
author: VienosNotes
logo: static/img/avatar.jpg
github: https://github.com/VienosNotes
about: SIerの下請け奴隷

baseurl: ""
url: "http://vienosnotes.github.io/"

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
