title: Vieno's Leaky Life
description: 雨漏りの雫のような生活
author: VienosNotes
logo: /static/img/avatar.png
github: https://github.com/VienosNotes
about: 雨漏りの雫のような生活

baseurl: ""
url: "http://pages.vno.jp/"

paginate: 10
paginate_path: "/contents/diary/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
category-list: [diary, article]
